spring.application.name=productivity

# Database connection
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.yoizesrrtqunsvwvqdaj&password=Happycabbage1###
spring.datasource.username=postgres
spring.datasource.password=Happycabbage1###

# JPA configuration
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true

# JWT
jwt.secret = this-is-my-jwt-secret-and-only-the-server-knows
jwt.expiration = 1h

logging.level.org.springframework.security=DEBUG
